model_path: /home/chaoxue/code/mol_opt/weight/3cl_affinity.tar
library_path: ./data/3CL_ZINC/library.csv
library_builtin_model_path: ./test/builtin_model/3cl_affinity.tar 

# Required
window_size: 2000
alpha: 0.75
max_iteration: 10
